from keras.models import Sequential,Model
from keras.layers import Convolution2D,MaxPool2D,Flatten,Dense,Dropout,Lambda
from keras.callbacks import TensorBoard
import numpy as np
import numpy as np
import scipy.io as scio
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras import models